# import libraries

In [5]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Generators
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

# generate recommendations

In [6]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = ['IBP'] * 2 + ['LOV'] * 2 + ['DCF'] * 2 + ['GLV'] * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 1
Very Important: Please Confirm the Iteration Number is Iteration 1
Very Important: Please Confirm the Iteration Number is Iteration 1

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'LOV', 'LOV', 'DCF', 'DCF', 'GLV', 'GLV']

In [7]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 3)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  8 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Ibuprofen IBP  | Iteration:  1

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

TypeError: obj is not an instance of cls: obj=9bbca800b7809a6c887bcbfb1b13a400 cls=<class 'typing.SupportsFloat'>

In [5]:
all_gens = list(Generators)

for gen in all_gens:
    print(gen)

Generators.SOBOL
Generators.FACTORIAL
Generators.SAASBO
Generators.SAAS_MTGP
Generators.THOMPSON
Generators.LEGACY_BOTORCH
Generators.BOTORCH_MODULAR
Generators.EMPIRICAL_BAYES_THOMPSON
Generators.EB_ASHR
Generators.UNIFORM
Generators.ST_MTGP
Generators.BO_MIXED
Generators.CONTEXT_SACBO

# process results

In [6]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.COMPLETED, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's8', 'surf_1_conc': 12, 'surf_2': 's6', 'surf_2_conc': 39, 'surf_3': 's7', 'surf_3_conc': 20, 'drug_conc': 25.0})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.COMPLETED, arm=Arm(name='1_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's3', 'surf_1_conc': 51, 'surf_2': 's2', 'surf_2_conc': 4, 'surf_3': 's6', 'surf_3_conc': 40, 'drug_conc': 25.0})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.COMPLETED, arm=Arm(name='2_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's5', 'surf_1_conc': 1, 'surf_2': 's7', 'surf_2_conc': 56, 'surf_3': 's3', 'surf_3_conc': 0, 'drug_conc': 25.0})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.COMPLETED, arm=Arm(name='3_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's3', 'surf_1_conc': 28, 'surf_2': 's3', 'surf_2_conc': 6, 'surf_3': 's8', 'surf_3_conc': 14, 'drug_conc': 25.0})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.COMPLETED, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's1', 'surf_1_conc': 27, 'surf_2': 's4', 'surf_2_conc': 63, 'surf_3': 's5', 'surf_3_conc': 3, 'drug_conc': 25.0})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.COMPLETED, arm=Arm(name='5_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's6', 'surf_1_conc': 40, 'surf_2': 's8', 'surf_2_conc': 29, 'surf_3': 's7', 'surf_3_conc': 22, 'drug_conc': 25.0})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.COMPLETED, arm=Arm(name='6_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's1', 'surf_1_conc': 5, 'surf_2': 's1', 'surf_2_conc': 24, 'surf_3': 's6', 'surf_3_conc': 18, 'drug_conc': 25.0})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.COMPLETED, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's6', 'surf_1_conc': 10, 'surf_2': 's5', 'surf_2_conc': 1, 'surf_3': 's1', 'surf_3_conc': 36, 'drug_conc': 25.0})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.COMPLETED, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's4', 'surf_1_conc': 4, 'surf_2': 's4', 'surf_2_conc': 15, 'surf_3': 's1', 'surf_3_conc': 50, 'drug_conc': 25.0})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.COMPLETED, arm=Arm(name='9_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's3', 'surf_1_conc': 37, 'surf_2': 's4', 'surf_2_conc': 17, 'surf_3': 's5', 'surf_3_conc': 32, 'drug_conc': 25.0})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.COMPLETED, arm=Arm(name='10_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's1', 'surf_1_conc': 30, 'surf_2': 's5', 'surf_2_conc': 3, 'surf_3': 's5', 'surf_3_conc': 54, 'drug_conc': 25.0})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.COMPLETED, arm=Arm(name='11_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's4', 'surf_1_conc': 22, 'surf_2': 's7', 'surf_2_conc': 37, 'surf_3': 's3', 'surf_3_conc': 27, 'drug_conc': 25.0})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.COMPLETED, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's4', 'surf_1_conc': 59, 'surf_2': 's1', 'surf_2_conc': 21, 'surf_3': 's8', 'surf_3_conc': 6, 'drug_conc': 25.0})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.COMPLETED, arm=Arm(name='13_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's2', 'surf_1_conc': 10, 'surf_2': 's8', 'surf_2_conc': 78, 'surf_3': 's3', 'surf_3_conc': 9, 'drug_conc': 25.0})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.COMPLETED, arm=Arm(name='14_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's5', 'surf_1_conc': 22, 'surf_2': 's7', 'surf_2_conc': 17, 'surf_3': 's3', 'surf_3_conc': 16, 'drug_conc': 25.0})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.COMPLETED, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's5', 'surf_1_conc': 31, 'surf_2': 's4', 'surf_2_conc': 35, 'surf_3': 's1', 'surf_3_conc': 24, 'drug_conc': 25.0})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.COMPLETED, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's6', 'surf_1_conc': 50, 'surf_2': 's1', 'surf_2_conc': 0, 'surf_3': 's6', 'surf_3_conc': 13, 'drug_conc': 25.0})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.COMPLETED, arm=Arm(name='17_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's8', 'surf_1_conc': 8, 'surf_2': 's6', 'surf_2_conc': 46, 'surf_3': 's4', 'surf_3_conc': 20, 'drug_conc': 25.0})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.COMPLETED, arm=Arm(name='18_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's6', 'surf_1_conc': 20, 'surf_2': 's8', 'surf_2_conc': 62, 'surf_3': 's3', 'surf_3_conc': 1, 'drug_conc': 25.0})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.COMPLETED, arm=Arm(name='19_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's6', 'surf_1_conc': 0, 'surf_2': 's7', 'surf_2_conc': 30, 'surf_3': 's2', 'surf_3_conc': 25, 'drug_conc': 25.0})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.COMPLETED, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's4', 'surf_1_conc': 63, 'surf_2': 's4', 'surf_2_conc': 14, 'surf_3': 's1', 'surf_3_conc': 9, 'drug_conc': 25.0})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.COMPLETED, arm=Arm(name='21_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's3', 'surf_1_conc': 41, 'surf_2': 's7', 'surf_2_conc': 22, 'surf_3': 's7', 'surf_3_conc': 34, 'drug_conc': 25.0})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.COMPLETED, arm=Arm(name='22_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's5', 'surf_1_conc': 28, 'surf_2': 's6', 'surf_2_conc': 39, 'surf_3': 's1', 'surf_3_conc': 29, 'drug_conc': 25.0})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.COMPLETED, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's4', 'surf_1_conc': 23, 'surf_2': 's4', 'surf_2_conc': 20, 'surf_3': 's5', 'surf_3_conc': 53, 'drug_conc': 25.0})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.COMPLETED, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's5', 'surf_1_conc': 18, 'surf_2': 's1', 'surf_2_conc': 9, 'surf_3': 's1', 'surf_3_conc': 36, 'drug_conc': 25.0})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.COMPLETED, arm=Arm(name='25_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1': 's1', 'surf_1_conc': 24, 'surf_2': 's6', 'surf_2_conc': 12, 'surf_3': 's8', 'surf_3_conc': 13, 'drug_conc': 25.0})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.COMPLETED, arm=Arm(name='26_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's7', 'surf_1_conc': 33, 'surf_2': 's2', 'surf_2_conc': 41, 'surf_3': 's3', 'surf_3_conc': 21, 'drug_conc': 25.0})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.COMPLETED, arm=Arm(name='27_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1': 's1', 'surf_1_conc': 47, 'surf_2': 's8', 'surf_2_conc': 51, 'surf_3': 's6', 'surf_3_conc': 1, 'drug_conc': 25.0})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.COMPLETED, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's4', 'surf_1_conc': 48, 'surf_2': 's2', 'surf_2_conc': 19, 'surf_3': 's2', 'surf_3_conc': 15, 'drug_conc': 25.0})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.COMPLETED, arm=Arm(name='29_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1': 's2', 'surf_1_conc': 19, 'surf_2': 's6', 'surf_2_conc': 68, 'surf_3': 's5', 'surf_3_conc': 5, 'drug_conc': 25.0})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.COMPLETED, arm=Arm(name='30_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's1', 'surf_1_conc': 7, 'surf_2': 's2', 'surf_2_conc': 27, 'surf_3': 's1', 'surf_3_conc': 25, 'drug_conc': 25.0})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.COMPLETED, arm=Arm(name='31_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1': 's7', 'surf_1_conc': 65, 'surf_2': 's4', 'surf_2_conc': 9, 'surf_3': 's4', 'surf_3_conc': 11, 'drug_conc': 25.0})),
 32: Trial(experiment_name='drug_surfactant', index=32, status=TrialStatus.RUNNING, arm=Arm(name='32_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 24, 'surf_2_conc': 8, 'surf_3_conc': 19, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 33: Trial(experiment_name='drug_surfactant', index=33, status=TrialStatus.RUNNING, arm=Arm(name='33_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 24, 'surf_2_conc': 3, 'surf_3_conc': 19, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 34: Trial(experiment_name='drug_surfactant', index=34, status=TrialStatus.RUNNING, arm=Arm(name='34_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 24, 'surf_2_conc': 15, 'surf_3_conc': 11, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 35: Trial(experiment_name='drug_surfactant', index=35, status=TrialStatus.RUNNING, arm=Arm(name='35_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 24, 'surf_2_conc': 11, 'surf_3_conc': 20, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 36: Trial(experiment_name='drug_surfactant', index=36, status=TrialStatus.RUNNING, arm=Arm(name='36_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 24, 'surf_2_conc': 15, 'surf_3_conc': 18, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 37: Trial(experiment_name='drug_surfactant', index=37, status=TrialStatus.RUNNING, arm=Arm(name='37_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 24, 'surf_2_conc': 17, 'surf_3_conc': 11, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 38: Trial(experiment_name='drug_surfactant', index=38, status=TrialStatus.RUNNING, arm=Arm(name='38_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 26, 'surf_2_conc': 6, 'surf_3_conc': 23, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'})),
 39: Trial(experiment_name='drug_surfactant', index=39, status=TrialStatus.RUNNING, arm=Arm(name='39_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 24, 'surf_2_conc': 12, 'surf_3_conc': 8, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's8'}))}

In [7]:
ax_client.get_trials_data_frame()

/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1,surf_1_conc,surf_2,surf_2_conc,surf_3,surf_3_conc,drug_conc
0,0,0_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s8,12,s6,39,s7,20,25.0
1,1,1_0,COMPLETED,None,95.0,0.2063,0.3073,0.0373,s3,51,s2,4,s6,40,25.0
2,2,2_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s5,1,s7,56,s3,0,25.0
3,3,3_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s3,28,s3,6,s8,14,25.0
4,4,4_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s1,27,s4,63,s5,3,25.0
5,5,5_0,COMPLETED,None,91.0,0.2962,0.4364,0.0493,s6,40,s8,29,s7,22,25.0
6,6,6_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s1,5,s1,24,s6,18,25.0
7,7,7_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s6,10,s5,1,s1,36,25.0
8,8,8_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s4,4,s4,15,s1,50,25.0
9,9,9_0,COMPLETED,None,86.0,0.2063,0.3073,0.0373,s3,37,s4,17,s5,32,25.0
10,10,10_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s1,30,s5,3,s5,54,25.0
11,11,11_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s4,22,s7,37,s3,27,25.0
12,12,12_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s4,59,s1,21,s8,6,25.0
13,13,13_0,COMPLETED,None,97.0,0.2962,0.4364,0.0493,s2,10,s8,78,s3,9,25.0
14,14,14_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s5,22,s7,17,s3,16,25.0
15,15,15_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s5,31,s4,35,s1,24,25.0
16,16,16_0,COMPLETED,None,63.0,0.2063,0.3073,0.0373,s6,50,s1,0,s6,13,25.0
17,17,17_0,COMPLETED,None,74.0,0.2063,0.3073,0.0373,s8,8,s6,46,s4,20,25.0
18,18,18_0,COMPLETED,None,83.0,0.4045,0.4196,0.0728,s6,20,s8,62,s3,1,25.0
19,19,19_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s6,0,s7,30,s2,25,25.0
20,20,20_0,COMPLETED,None,86.0,0.2962,0.4364,0.0493,s4,63,s4,14,s1,9,25.0
21,21,21_0,COMPLETED,None,97.0,0.2962,0.4364,0.0493,s3,41,s7,22,s7,34,25.0
22,22,22_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s5,28,s6,39,s1,29,25.0
23,23,23_0,COMPLETED,None,96.0,0.3528,0.2810,0.0711,s4,23,s4,20,s5,53,25.0
24,24,24_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s5,18,s1,9,s1,36,25.0
25,25,25_0,COMPLETED,None,49.0,0.2063,0.3073,0.0373,s1,24,s6,12,s8,13,25.0
26,26,26_0,COMPLETED,None,95.0,0.4045,0.4196,0.0728,s7,33,s2,41,s3,21,25.0
27,27,27_0,COMPLETED,None,99.0,0.4045,0.4196,0.0728,s1,47,s8,51,s6,1,25.0
28,28,28_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s4,48,s2,19,s2,15,25.0
29,29,29_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s2,19,s6,68,s5,5,25.0
30,30,30_0,COMPLETED,None,59.0,0.3528,0.2810,0.0711,s1,7,s2,27,s1,25,25.0
31,31,31_0,COMPLETED,None,85.0,0.3528,0.2810,0.0711,s7,65,s4,9,s4,11,25.0
32,32,32_0,RUNNING,GenerationStep_0,NaN,0.2063,0.3073,0.0373,s1,24,s6,8,s8,19,25.0
33,33,33_0,RUNNING,GenerationStep_0,NaN,0.2063,0.3073,0.0373,s1,24,s6,3,s8,19,25.0
34,34,34_0,RUNNING,GenerationStep_0,NaN,0.4045,0.4196,0.0728,s1,24,s6,15,s8,11,25.0
35,35,35_0,RUNNING,GenerationStep_0,NaN,0.4045,0.4196,0.0728,s1,24,s6,11,s8,20,25.0
36,36,36_0,RUNNING,GenerationStep_0,NaN,0.2962,0.4364,0.0493,s1,24,s6,15,s8,18,25.0
37,37,37_0,RUNNING,GenerationStep_0,NaN,0.2962,0.4364,0.0493,s1,24,s6,17,s8,11,25.0
38,38,38_0,RUNNING,GenerationStep_0,NaN,0.3528,0.2810,0.0711,s1,26,s6,6,s8,23,25.0
39,39,39_0,RUNNING,GenerationStep_0,NaN,0.3528,0.2810,0.0711,s1,24,s6,12,s8,8,25.0

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,32,IBP,0.2063,0.3073,0.0373,24,17,9,25.0,s1,s6,s8,50,NaN
1,33,IBP,0.2063,0.3073,0.0373,24,14,8,25.0,s1,s6,s8,46,NaN
2,34,LOV,0.4045,0.4196,0.0728,24,9,11,25.0,s1,s6,s8,44,NaN
3,35,LOV,0.4045,0.4196,0.0728,24,17,11,25.0,s1,s6,s8,52,NaN
4,36,DCF,0.2962,0.4364,0.0493,24,12,22,25.0,s1,s6,s8,58,NaN
5,37,DCF,0.2962,0.4364,0.0493,24,1,19,25.0,s1,s6,s8,44,NaN
6,38,GLV,0.3528,0.2810,0.0711,23,14,11,25.0,s1,s6,s8,48,NaN
7,39,GLV,0.3528,0.2810,0.0711,22,10,11,25.0,s1,s6,s8,43,NaN

In [ ]:
df_vol

In [ ]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

In [ ]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

In [ ]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.1)
df_absorbance

In [ ]:
results = hf.build_results(n, df_absorbance)
results

# load the results to the optimizer

In [ ]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client