# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.factory import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy      
import helper_functions as hf

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 05-29 12:34:04] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 05-29 12:34:04] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='s1', parameter_type=INT, range=[0, 100]), RangeParameter(name='s2', parameter_type=INT, range=[0, 100]), RangeParameter(name='s3', parameter_type=INT, range=[0, 100]), RangeParameter(name='s4', parameter_type=INT, range=[0, 100]), RangeParameter(name='s5', parameter_type=INT, range=[0, 100]), RangeParameter(name='s6', parameter_type=INT, range=[0, 100]), RangeParameter(name='s7', parameter_type=INT, range=[0, 100]), RangeParameter(name='s8', parameter_type=INT, range=[0, 100]), RangeParameter(name='s9', parameter_type=INT, range=[0, 100]), RangeParameter(name='s10', parameter_type=INT, range=[0, 100]), RangeParameter(name='s11', parameter_type=INT, range=[0, 100]), RangeParameter(name='s12', parameter_type=INT, range=[0, 100]), RangeParameter(name='surfactant_conc', parameter_type=INT, range=[1, 100]), RangeParameter(name='drug_conc', parameter_type=INT, range=[1, 100])], parameter_constraints=[]).

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

[INFO 05-29 12:34:04] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_00.json`.

# iteration_0 + date

In [5]:
n = int(input("Enter the Iteration Number: "))

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

In [6]:
df_design, ax_client = hf.run_optimizer(current_iteration=n, n_trials=16)

[INFO 05-29 12:34:11] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 0 with parameters {'s1': 47, 's2': 59, 's3': 49, 's4': 31, 's5': 96, 's6': 8, 's7': 9, 's8': 35, 's9': 85, 's10': 76, 's11': 89, 's12': 88, 'surfactant_conc': 81, 'drug_conc': 86} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 1 with parameters {'s1': 93, 's2': 38, 's3': 50, 's4': 84, 's5': 50, 's6': 65, 's7': 78, 's8': 53, 's9': 26, 's10': 20, 's11': 36, 's12': 5, 'surfactant_conc': 29, 'drug_conc': 1} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 2 with parameters {'s1': 51, 's2': 77, 's3': 13, 's4': 24, 's5': 19, 's6': 94, 's7': 27, 's8': 92, 's9': 2, 's10': 28, 's11': 16, 's12': 30, 'surfactant_conc': 60, 'drug_conc': 53} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 3 with parameters {'s1': 8, 's2': 20, 's3': 88, 's4': 72, 's5': 73, 's6': 36, 's7': 60, 's8': 21, 's9': 62, 's10': 75, 's11': 58, 's12': 63, 'surfactant_conc': 12, 'drug_conc': 38} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 4 with parameters {'s1': 22, 's2': 93, 's3': 75, 's4': 52, 's5': 54, 's6': 24, 's7': 49, 's8': 77, 's9': 22, 's10': 5, 's11': 7, 's12': 56, 'surfactant_conc': 71, 'drug_conc': 19} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 5 with parameters {'s1': 68, 's2': 10, 's3': 25, 's4': 0, 's5': 1, 's6': 56, 's7': 64, 's8': 10, 's9': 63, 's10': 97, 's11': 66, 's12': 38, 'surfactant_conc': 19, 'drug_conc': 97} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 6 with parameters {'s1': 76, 's2': 75, 's3': 89, 's4': 91, 's5': 30, 's6': 78, 's7': 13, 's8': 47, 's9': 90, 's10': 52, 's11': 86, 's12': 13, 'surfactant_conc': 89, 'drug_conc': 45} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 7 with parameters {'s1': 34, 's2': 29, 's3': 12, 's4': 43, 's5': 78, 's6': 46, 's7': 100, 's8': 66, 's9': 50, 's10': 45, 's11': 38, 's12': 81, 'surfactant_conc': 40, 'drug_conc': 67} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 8 with parameters {'s1': 27, 's2': 82, 's3': 98, 's4': 10, 's5': 38, 's6': 30, 's7': 40, 's8': 86, 's9': 14, 's10': 69, 's11': 48, 's12': 94, 'surfactant_conc': 15, 'drug_conc': 38} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 9 with parameters {'s1': 82, 's2': 15, 's3': 1, 's4': 61, 's5': 92, 's6': 100, 's7': 73, 's8': 2, 's9': 73, 's10': 35, 's11': 78, 's12': 11, 'surfactant_conc': 64, 'drug_conc': 73} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 10 with parameters {'s1': 74, 's2': 51, 's3': 65, 's4': 45, 's5': 65, 's6': 72, 's7': 23, 's8': 41, 's9': 99, 's10': 14, 's11': 70, 's12': 36, 'surfactant_conc': 45, 'drug_conc': 25} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 11 with parameters {'s1': 16, 's2': 46, 's3': 36, 's4': 95, 's5': 17, 's6': 1, 's7': 90, 's8': 71, 's9': 39, 's10': 83, 's11': 5, 's12': 69, 'surfactant_conc': 97, 'drug_conc': 91} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 12 with parameters {'s1': 2, 's2': 67, 's3': 22, 's4': 80, 's5': 12, 's6': 39, 's7': 0, 's8': 28, 's9': 77, 's10': 39, 's11': 56, 's12': 62, 'surfactant_conc': 38, 'drug_conc': 59} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 13 with parameters {'s1': 57, 's2': 36, 's3': 77, 's4': 29, 's5': 58, 's6': 84, 's7': 86, 's8': 60, 's9': 35, 's10': 58, 's11': 20, 's12': 45, 'surfactant_conc': 86, 'drug_conc': 32} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 14 with parameters {'s1': 100, 's2': 98, 's3': 40, 's4': 63, 's5': 86, 's6': 62, 's7': 37, 's8': 96, 's9': 11, 's10': 91, 's11': 28, 's12': 20, 'surfactant_conc': 5, 'drug_conc': 79} using model Sobol.
/Users/zeqing/opt/anaconda3/envs/sdlnano_plot/lib/python3.11/site-packages/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 05-29 12:34:11] ax.service.ax_client: Generated new trial 15 with parameters {'s1': 41, 's2': 5, 's3': 61, 's4': 14, 's5': 32, 's6': 17, 's7': 51, 's8': 16, 's9': 52, 's10': 12, 's11': 99, 's12': 88, 'surfactant_conc': 56, 'drug_conc': 7} using model Sobol.
[INFO 05-29 12:34:11] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0.json`.

In [7]:
df_conc, df_vol = hf.design_to_conc_to_vol (df_design)

In [8]:
df_absorbance = hf.process_absorbance(iteration=n)
df_absorbance

    trial_index  success
0             0        1
1             1        0
2             2        0
3             3        0
4             4        0
5             5        1
6             6        0
7             7        0
8             8        1
9             9        1
10           10        1
11           11        1
12           12        1
13           13        1
14           14        1
15           15        1
16           16        1
17           17        1
18           18        1
19           19        1
20           20        1
21           21        1
22           22        1
23           23        1

In [9]:
results = hf.build_results(df_design, df_conc, df_absorbance)
results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,85,76,89,88,40.5,21.50,1,2.150,12
1,1,93,38,50,84,50,65,78,53,26,20,36,5,14.5,0.25,0,0.000,12
2,2,51,77,13,24,19,94,27,92,2,28,16,30,30.0,13.25,0,0.000,12
3,3,8,20,88,72,73,36,60,21,62,75,58,63,6.0,9.50,0,0.000,12
4,4,22,93,75,52,54,24,49,77,22,5,7,56,35.5,4.75,0,0.000,12
5,5,68,10,25,0,1,56,64,10,63,97,66,38,9.5,24.25,1,2.425,11
6,6,76,75,89,91,30,78,13,47,90,52,86,13,44.5,11.25,0,0.000,12
7,7,34,29,12,43,78,46,100,66,50,45,38,81,20.0,16.75,0,0.000,12
8,8,27,82,98,10,38,30,40,86,14,69,48,94,7.5,9.50,1,0.950,12
9,9,82,15,1,61,92,100,73,2,73,35,78,11,32.0,18.25,1,1.825,12
10,10,74,51,65,45,65,72,23,41,99,14,70,36,22.5,6.25,1,0.625,12
11,11,16,46,36,95,17,1,90,71,39,83,5,69,48.5,22.75,1,2.275,12
12,12,2,67,22,80,12,39,0,28,77,39,56,62,19.0,14.75,1,1.475,11
13,13,57,36,77,29,58,84,86,60,35,58,20,45,43.0,8.00,1,0.800,12
14,14,100,98,40,63,86,62,37,96,11,91,28,20,2.5,19.75,1,1.975,12
15,15,41,5,61,14,32,17,51,16,52,12,99,88,28.0,1.75,1,0.175,12

In [10]:
norm_results = hf.normalize_data(results, 'normalize')
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,85,76,89,88,0.81,21.50,1,0.86,1.000000
1,1,93,38,50,84,50,65,78,53,26,20,36,5,0.29,0.25,0,0.00,1.000000
2,2,51,77,13,24,19,94,27,92,2,28,16,30,0.60,13.25,0,0.00,1.000000
3,3,8,20,88,72,73,36,60,21,62,75,58,63,0.12,9.50,0,0.00,1.000000
4,4,22,93,75,52,54,24,49,77,22,5,7,56,0.71,4.75,0,0.00,1.000000
5,5,68,10,25,0,1,56,64,10,63,97,66,38,0.19,24.25,1,0.97,0.916667
6,6,76,75,89,91,30,78,13,47,90,52,86,13,0.89,11.25,0,0.00,1.000000
7,7,34,29,12,43,78,46,100,66,50,45,38,81,0.40,16.75,0,0.00,1.000000
8,8,27,82,98,10,38,30,40,86,14,69,48,94,0.15,9.50,1,0.38,1.000000
9,9,82,15,1,61,92,100,73,2,73,35,78,11,0.64,18.25,1,0.73,1.000000
10,10,74,51,65,45,65,72,23,41,99,14,70,36,0.45,6.25,1,0.25,1.000000
11,11,16,46,36,95,17,1,90,71,39,83,5,69,0.97,22.75,1,0.91,1.000000
12,12,2,67,22,80,12,39,0,28,77,39,56,62,0.38,14.75,1,0.59,0.916667
13,13,57,36,77,29,58,84,86,60,35,58,20,45,0.86,8.00,1,0.32,1.000000
14,14,100,98,40,63,86,62,37,96,11,91,28,20,0.05,19.75,1,0.79,1.000000
15,15,41,5,61,14,32,17,51,16,52,12,99,88,0.56,1.75,1,0.07,1.000000

In [11]:
back = hf.normalize_data(norm_results, 'denormalize')
back

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,85,76,89,88,40.5,21.50,1,2.150,12.0
1,1,93,38,50,84,50,65,78,53,26,20,36,5,14.5,0.25,0,0.000,12.0
2,2,51,77,13,24,19,94,27,92,2,28,16,30,30.0,13.25,0,0.000,12.0
3,3,8,20,88,72,73,36,60,21,62,75,58,63,6.0,9.50,0,0.000,12.0
4,4,22,93,75,52,54,24,49,77,22,5,7,56,35.5,4.75,0,0.000,12.0
5,5,68,10,25,0,1,56,64,10,63,97,66,38,9.5,24.25,1,2.425,11.0
6,6,76,75,89,91,30,78,13,47,90,52,86,13,44.5,11.25,0,0.000,12.0
7,7,34,29,12,43,78,46,100,66,50,45,38,81,20.0,16.75,0,0.000,12.0
8,8,27,82,98,10,38,30,40,86,14,69,48,94,7.5,9.50,1,0.950,12.0
9,9,82,15,1,61,92,100,73,2,73,35,78,11,32.0,18.25,1,1.825,12.0
10,10,74,51,65,45,65,72,23,41,99,14,70,36,22.5,6.25,1,0.625,12.0
11,11,16,46,36,95,17,1,90,71,39,83,5,69,48.5,22.75,1,2.275,12.0
12,12,2,67,22,80,12,39,0,28,77,39,56,62,19.0,14.75,1,1.475,11.0
13,13,57,36,77,29,58,84,86,60,35,58,20,45,43.0,8.00,1,0.800,12.0
14,14,100,98,40,63,86,62,37,96,11,91,28,20,2.5,19.75,1,1.975,12.0
15,15,41,5,61,14,32,17,51,16,52,12,99,88,28.0,1.75,1,0.175,12.0

In [12]:
norm_results

,trial_index,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,surfactant_conc,drug_conc,success,micelle_drug_conc,complexity
0,0,47,59,49,31,96,8,9,35,85,76,89,88,0.81,21.50,1,0.86,1.000000
1,1,93,38,50,84,50,65,78,53,26,20,36,5,0.29,0.25,0,0.00,1.000000
2,2,51,77,13,24,19,94,27,92,2,28,16,30,0.60,13.25,0,0.00,1.000000
3,3,8,20,88,72,73,36,60,21,62,75,58,63,0.12,9.50,0,0.00,1.000000
4,4,22,93,75,52,54,24,49,77,22,5,7,56,0.71,4.75,0,0.00,1.000000
5,5,68,10,25,0,1,56,64,10,63,97,66,38,0.19,24.25,1,0.97,0.916667
6,6,76,75,89,91,30,78,13,47,90,52,86,13,0.89,11.25,0,0.00,1.000000
7,7,34,29,12,43,78,46,100,66,50,45,38,81,0.40,16.75,0,0.00,1.000000
8,8,27,82,98,10,38,30,40,86,14,69,48,94,0.15,9.50,1,0.38,1.000000
9,9,82,15,1,61,92,100,73,2,73,35,78,11,0.64,18.25,1,0.73,1.000000
10,10,74,51,65,45,65,72,23,41,99,14,70,36,0.45,6.25,1,0.25,1.000000
11,11,16,46,36,95,17,1,90,71,39,83,5,69,0.97,22.75,1,0.91,1.000000
12,12,2,67,22,80,12,39,0,28,77,39,56,62,0.38,14.75,1,0.59,0.916667
13,13,57,36,77,29,58,84,86,60,35,58,20,45,0.86,8.00,1,0.32,1.000000
14,14,100,98,40,63,86,62,37,96,11,91,28,20,0.05,19.75,1,0.79,1.000000
15,15,41,5,61,14,32,17,51,16,52,12,99,88,0.56,1.75,1,0.07,1.000000

In [13]:
ax_client = hf.load_data_to_optimizer(iteration = n, norm_results = norm_results)
ax_client

[INFO 05-29 12:34:21] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 0 with data: {'micelle_drug_conc': (0.86, None), 'surfactant_conc': (0.81, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 1 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.29, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 2 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.6, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 3 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.12, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 4 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.71, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 5 with data: {'micelle_drug_conc': (0.97, None), 'surfactant_conc': (0.19, None), 'complexity': (0.916667, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 6 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.89, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 7 with data: {'micelle_drug_conc': (0.0, None), 'surfactant_conc': (0.4, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 8 with data: {'micelle_drug_conc': (0.38, None), 'surfactant_conc': (0.15, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 9 with data: {'micelle_drug_conc': (0.73, None), 'surfactant_conc': (0.64, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 10 with data: {'micelle_drug_conc': (0.25, None), 'surfactant_conc': (0.45, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 11 with data: {'micelle_drug_conc': (0.91, None), 'surfactant_conc': (0.97, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 12 with data: {'micelle_drug_conc': (0.59, None), 'surfactant_conc': (0.38, None), 'complexity': (0.916667, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 13 with data: {'micelle_drug_conc': (0.32, None), 'surfactant_conc': (0.86, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 14 with data: {'micelle_drug_conc': (0.79, None), 'surfactant_conc': (0.05, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Completed trial 15 with data: {'micelle_drug_conc': (0.07, None), 'surfactant_conc': (0.56, None), 'complexity': (1.0, None)}.
[INFO 05-29 12:34:21] ax.service.ax_client: Saved JSON-serialized state of optimization to `optimizer/optimizer_0_loaded.json`.

AxClient(experiment=Experiment(drug_surfactant))

In [14]:
ax_client

AxClient(experiment=Experiment(drug_surfactant))

In [15]:
df = ax_client.get_trials_data_frame()
df

,trial_index,arm_name,trial_status,generation_method,generation_node,complexity,micelle_drug_conc,surfactant_conc,s1,s2,...,s4,s5,s6,s7,s8,s9,s10,s11,s12,drug_conc
0,0,0_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.86,81,47,59,...,31,96,8,9,35,85,76,89,88,86
1,1,1_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.00,29,93,38,...,84,50,65,78,53,26,20,36,5,1
2,2,2_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.00,60,51,77,...,24,19,94,27,92,2,28,16,30,53
3,3,3_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.00,12,8,20,...,72,73,36,60,21,62,75,58,63,38
4,4,4_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.00,71,22,93,...,52,54,24,49,77,22,5,7,56,19
5,5,5_0,COMPLETED,Sobol,GenerationStep_0,0.916667,0.97,19,68,10,...,0,1,56,64,10,63,97,66,38,97
6,6,6_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.00,89,76,75,...,91,30,78,13,47,90,52,86,13,45
7,7,7_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.00,40,34,29,...,43,78,46,100,66,50,45,38,81,67
8,8,8_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.38,15,27,82,...,10,38,30,40,86,14,69,48,94,38
9,9,9_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.73,64,82,15,...,61,92,100,73,2,73,35,78,11,73
10,10,10_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.25,45,74,51,...,45,65,72,23,41,99,14,70,36,25
11,11,11_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.91,97,16,46,...,95,17,1,90,71,39,83,5,69,91
12,12,12_0,COMPLETED,Sobol,GenerationStep_0,0.916667,0.59,38,2,67,...,80,12,39,0,28,77,39,56,62,59
13,13,13_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.32,86,57,36,...,29,58,84,86,60,35,58,20,45,32
14,14,14_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.79,5,100,98,...,63,86,62,37,96,11,91,28,20,79
15,15,15_0,COMPLETED,Sobol,GenerationStep_0,1.000000,0.07,56,41,5,...,14,32,17,51,16,52,12,99,88,7