# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf

/var/folders/9p/f66yhymx35939zzlg51g0rrc0000gn/T/ipykernel_6531/3307975217.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP']  + ['LOV']  + ['DCF']  + ['GLV']) * 1

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 7
Very Important: Please Confirm the Iteration Number is Iteration 7
Very Important: Please Confirm the Iteration Number is Iteration 7

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV']

In [3]:
time_start = time.time()


df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 2)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

**************************************************************************************************** 1  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Ibuprofen IBP  | Iteration:  7

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 16:23:49] ax.service.ax_client: Generated new trial 56 with parameters {'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 36, 'surf_2_conc': 17, 'surf_3_conc': 3, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's6', 'surf_3': 's6'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 2  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Lovastatin LOV  | Iteration:  7

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 16:23:58] ax.service.ax_client: Generated new trial 57 with parameters {'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 0, 'surf_2_conc': 0, 'surf_3_conc': 100, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's2'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 3  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Diclofenac DCF  | Iteration:  7

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 16:24:05] ax.service.ax_client: Generated new trial 58 with parameters {'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 16, 'surf_2_conc': 0, 'surf_3_conc': 63, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's6', 'surf_3': 's8'} using model SAASBO.
/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

**************************************************************************************************** 4  out of  4 ****************************************************************************************************
********************************************************************************************************************************************************************************************************

Drug name:  Griseofulvin GLV  | Iteration:  7

********************************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************************

[INFO 07-18 16:24:15] ax.service.ax_client: Generated new trial 59 with parameters {'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 0, 'surf_2_conc': 0, 'surf_3_conc': 100, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's6', 'surf_3': 's2'} using model SAASBO.

Time taken for optimization: 0.88 mins
Time taken for optimization: 52.8 seconds

# process results

In [4]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1,surf_1_conc,surf_2,surf_2_conc,surf_3,surf_3_conc,drug_conc
0,0,0_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s8,12,s6,39,s7,20,25.0
1,1,1_0,COMPLETED,None,95.0,0.2063,0.3073,0.0373,s3,51,s2,4,s6,40,25.0
2,2,2_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s5,1,s7,56,s3,0,25.0
3,3,3_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s3,28,s3,6,s8,14,25.0
4,4,4_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s1,27,s4,63,s5,3,25.0
5,5,5_0,COMPLETED,None,91.0,0.2962,0.4364,0.0493,s6,40,s8,29,s7,22,25.0
6,6,6_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s1,5,s1,24,s6,18,25.0
7,7,7_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s6,10,s5,1,s1,36,25.0
8,8,8_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s4,4,s4,15,s1,50,25.0
9,9,9_0,COMPLETED,None,86.0,0.2063,0.3073,0.0373,s3,37,s4,17,s5,32,25.0
10,10,10_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s1,30,s5,3,s5,54,25.0
11,11,11_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s4,22,s7,37,s3,27,25.0
12,12,12_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s4,59,s1,21,s8,6,25.0
13,13,13_0,COMPLETED,None,97.0,0.2962,0.4364,0.0493,s2,10,s8,78,s3,9,25.0
14,14,14_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s5,22,s7,17,s3,16,25.0
15,15,15_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s5,31,s4,35,s1,24,25.0
16,16,16_0,COMPLETED,None,63.0,0.2063,0.3073,0.0373,s6,50,s1,0,s6,13,25.0
17,17,17_0,COMPLETED,None,74.0,0.2063,0.3073,0.0373,s8,8,s6,46,s4,20,25.0
18,18,18_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s6,20,s8,62,s3,1,25.0
19,19,19_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s6,0,s7,30,s2,25,25.0
20,20,20_0,COMPLETED,None,86.0,0.2962,0.4364,0.0493,s4,63,s4,14,s1,9,25.0
21,21,21_0,COMPLETED,None,97.0,0.2962,0.4364,0.0493,s3,41,s7,22,s7,34,25.0
22,22,22_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s5,28,s6,39,s1,29,25.0
23,23,23_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s4,23,s4,20,s5,53,25.0
24,24,24_0,COMPLETED,None,100.0,0.2063,0.3073,0.0373,s5,18,s1,9,s1,36,25.0
25,25,25_0,COMPLETED,None,49.0,0.2063,0.3073,0.0373,s1,24,s6,12,s8,13,25.0
26,26,26_0,COMPLETED,None,100.0,0.4045,0.4196,0.0728,s7,33,s2,41,s3,21,25.0
27,27,27_0,COMPLETED,None,99.0,0.4045,0.4196,0.0728,s1,47,s8,51,s6,1,25.0
28,28,28_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s4,48,s2,19,s2,15,25.0
29,29,29_0,COMPLETED,None,100.0,0.2962,0.4364,0.0493,s2,19,s6,68,s5,5,25.0
30,30,30_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s1,7,s2,27,s1,25,25.0
31,31,31_0,COMPLETED,None,100.0,0.3528,0.2810,0.0711,s7,65,s4,9,s4,11,25.0
32,32,32_0,COMPLETED,GenerationStep_2,100.0,0.2063,0.3073,0.0373,s1,0,s6,0,s8,0,25.0
33,33,33_0,COMPLETED,GenerationStep_2,100.0,0.4045,0.4196,0.0728,s1,0,s6,0,s8,0,25.0
34,34,34_0,COMPLETED,GenerationStep_2,100.0,0.2962,0.4364,0.0493,s1,0,s6,0,s8,0,25.0
35,35,35_0,COMPLETED,GenerationStep_2,100.0,0.3528,0.2810,0.0711,s1,0,s6,0,s8,0,25.0
36,36,36_0,COMPLETED,GenerationStep_2,55.0,0.2063,0.3073,0.0373,s1,30,s6,12,s8,13,25.0
37,37,37_0,COMPLETED,GenerationStep_2,100.0,0.4045,0.4196,0.0728,s1,30,s6,12,s8,13,25.0
38,38,38_0,COMPLETED,GenerationStep_2,100.0,0.2962,0.4364,0.0493,s1,30,s6,12,s8,13,25.0
39,39,39_0,COMPLETED,GenerationStep_2,100.0,0.3528,0.2810,0.0711,s1,30,s6,12,s8,13,25.0
40,40,40_0,COMPLETED,GenerationStep_2,94.0,0.2063,0.3073,0.0373,s1,42,s6,26,s8,26,25.0
41,41,41_0,COMPLETED,GenerationStep_2,82.0,0.4045,0.4196,0.0728,s1,33,s6,14,s8,35,25.0
42,42,42_0,COMPLETED,GenerationStep_2,76.0,0.2962,0.4364,0.0493,s1,38,s6,10,s8,28,25.0
43,43,43_0,COMPLETED,GenerationStep_2,89.0,0.3528,0.2810,0.0711,s1,48,s6,16,s8,25,25.0
44,44,44_0,COMPLETED,GenerationStep_2,14.0,0.2063,0.3073,0.0373,s1,1,s6,0,s8,13,25.0
45,45,45_0,COMPLETED,GenerationStep_2,100.0,0.4045,0.4196,0.0728,s2,0,s2,0,s7,100,25.0
46,46,46_0,COMPLETED,GenerationStep_2,100.0,0.2962,0.4364,0.0493,s2,0,s2,0,s7,100,25.0
47,47,47_0,COMPLETED,GenerationStep_2,100.0,0.3528,0.2810,0.0711,s8,0,s2,0,s7,100,25.0
48,48,48_0,COMPLETED,GenerationStep_2,100.0,0.2063,0.3073,0.0373,s1,0,s6,0,s8,16,25.0
49,49,49_0,COMPLETED,GenerationStep_2,100.0,0.4045,0.4196,0.0728,s1,0,s6,0,s8,33,25.0
50,50,50_0,COMPLETED,GenerationStep_2,100.0,0.2962,0.4364,0.0493,s1,0,s6,0,s8,21,25.0
51,51,51_0,COMPLETED,GenerationStep_2,29.0,0.3528,0.2810,0.0711,s1,0,s6,0,s8,29,25.0
52,52,52_0,COMPLETED,GenerationStep_2,54.0,0.2063,0.3073,0.0373,s1,24,s6,0,s2,30,25.0
53,53,53_0,COMPLETED,GenerationStep_2,100.0,0.4045,0.4196,0.0728,s8,100,s6,0,s8,0,25.0
54,54,54_0,COMPLETED,GenerationStep_2,100.0,0.2962,0.4364,0.0493,s1,45,s6,0,s4,55,25.0
55,55,55_0,COMPLETED,GenerationStep_2,100.0,0.3528,0.2810,0.0711,s6,0,s6,0,s8,0,25.0
56,56,56_0,RUNNING,GenerationStep_2,NaN,0.2063,0.3073,0.0373,s6,36,s6,17,s6,3,25.0
57,57,57_0,RUNNING,GenerationStep_2,NaN,0.4045,0.4196,0.0728,s1,0,s6,0,s2,100,25.0
58,58,58_0,RUNNING,GenerationStep_2,NaN,0.2962,0.4364,0.0493,s3,16,s6,0,s8,63,25.0
59,59,59_0,RUNNING,GenerationStep_2,NaN,0.3528,0.2810,0.0711,s1,0,s6,0,s2,100,25.0

In [5]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc
0,56,IBP,0.2063,0.3073,0.0373,36,17,3,25.0,s6,s6,s6,56,NaN
1,57,LOV,0.4045,0.4196,0.0728,0,0,100,25.0,s1,s6,s2,100,NaN
2,58,DCF,0.2962,0.4364,0.0493,16,0,63,25.0,s3,s6,s8,79,NaN
3,59,GLV,0.3528,0.2810,0.0711,0,0,100,25.0,s1,s6,s2,100,NaN

In [6]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,56,IBP,180.0,0.0,0.0,0.0,0.0,0.0,672.0,0.0,0.0,0.0,528.0,180.0,0.0,0.0,0.0
1,57,LOV,180.0,0.0,1200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0,0.0,0.0
2,58,DCF,180.0,0.0,0.0,192.0,0.0,0.0,0.0,0.0,756.0,0.0,252.0,0.0,0.0,180.0,0.0
3,59,GLV,180.0,0.0,1200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0

In [7]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: F1
Deep plate will start at: F7

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [8]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_7.py

In [9]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        1
1            1        0
2            2        1
3            3        0

In [10]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,surf_3_conc,drug_conc,surf_1,surf_2,surf_3,surf_conc,obj_surf_conc,success
0,56,IBP,0.2063,0.3073,0.0373,36,17,3,25.0,s6,s6,s6,56,56,1
1,57,LOV,0.4045,0.4196,0.0728,0,0,100,25.0,s1,s6,s2,100,100,0
2,58,DCF,0.2962,0.4364,0.0493,16,0,63,25.0,s3,s6,s8,79,79,1
3,59,GLV,0.3528,0.2810,0.0711,0,0,100,25.0,s1,s6,s2,100,100,0

# load the results to the optimizer

In [11]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-21 09:24:17] ax.service.ax_client: Completed trial 56 with data: {'obj_surf_conc': (56.0, None)}.
[INFO 07-21 09:24:17] ax.service.ax_client: Completed trial 57 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-21 09:24:17] ax.service.ax_client: Completed trial 58 with data: {'obj_surf_conc': (79.0, None)}.
[INFO 07-21 09:24:17] ax.service.ax_client: Completed trial 59 with data: {'obj_surf_conc': (100.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))