# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time

import sys
sys.path.append('../')
import helper_functions as hf

C:\Users\yunhe\AppData\Local\Temp\ipykernel_25644\1711932296.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# initialize the optimizer

In [2]:
ax_client_init_file_name = 'optimizer/optimizer_00.json'
ax_client = hf.optimizer_init()
ax_client

[INFO 11-10 14:59:17] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_1". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 11-10 14:59:17] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter surf_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "surf_2". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(

AxClient(experiment=Experiment(drug_surfactant))

In [3]:
ax_client.save_to_json_file(ax_client_init_file_name)

# generate recommendations

In [4]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP'] + ['LOV']  + ['DCF']  + ['GLV'] ) * 8

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0
Very Important: Please Confirm the Iteration Number is Iteration 0

Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']
Very Important: Please Confirm the Drugs are:  ['IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV', 'IBP', 'LOV', 'DCF', 'GLV']

In [5]:
time_start = time.time()



df_design, ax_client = hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs, bopt=0)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/32 ********************************************************************************


******************************************************************************** 2/32 ********************************************************************************


******************************************************************************** 3/32 ********************************************************************************


******************************************************************************** 4/32 ********************************************************************************


******************************************************************************** 5/32 ********************************************************************************


******************************************************************************** 6/32 ********************************************************************************


******************************************************************************** 7/32 ********************************************************************************


******************************************************************************** 8/32 ********************************************************************************


******************************************************************************** 9/32 ********************************************************************************


******************************************************************************** 10/32 ********************************************************************************


******************************************************************************** 11/32 ********************************************************************************


******************************************************************************** 12/32 ********************************************************************************


******************************************************************************** 13/32 ********************************************************************************


******************************************************************************** 14/32 ********************************************************************************


******************************************************************************** 15/32 ********************************************************************************


******************************************************************************** 16/32 ********************************************************************************


******************************************************************************** 17/32 ********************************************************************************


******************************************************************************** 18/32 ********************************************************************************


******************************************************************************** 19/32 ********************************************************************************


******************************************************************************** 20/32 ********************************************************************************


******************************************************************************** 21/32 ********************************************************************************


******************************************************************************** 22/32 ********************************************************************************


******************************************************************************** 23/32 ********************************************************************************


******************************************************************************** 24/32 ********************************************************************************


******************************************************************************** 25/32 ********************************************************************************


******************************************************************************** 26/32 ********************************************************************************


******************************************************************************** 27/32 ********************************************************************************


******************************************************************************** 28/32 ********************************************************************************


******************************************************************************** 29/32 ********************************************************************************


******************************************************************************** 30/32 ********************************************************************************


******************************************************************************** 31/32 ********************************************************************************


******************************************************************************** 32/32 ********************************************************************************

KeyError: 'surf_1_conc'

# process results

In [ ]:
ax_client = hf.load_design_optimizer(n)
ax_client.experiment.trials

{0: Trial(experiment_name='drug_surfactant', index=0, status=TrialStatus.RUNNING, arm=Arm(name='0_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 29, 'surf_2_conc': 6, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's6'})),
 1: Trial(experiment_name='drug_surfactant', index=1, status=TrialStatus.RUNNING, arm=Arm(name='1_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 6, 'surf_2_conc': 44, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's4'})),
 2: Trial(experiment_name='drug_surfactant', index=2, status=TrialStatus.RUNNING, arm=Arm(name='2_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 4, 'surf_2_conc': 27, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's6'})),
 3: Trial(experiment_name='drug_surfactant', index=3, status=TrialStatus.RUNNING, arm=Arm(name='3_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 91, 'surf_2_conc': 1, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's2'})),
 4: Trial(experiment_name='drug_surfactant', index=4, status=TrialStatus.RUNNING, arm=Arm(name='4_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 32, 'surf_2_conc': 14, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's4'})),
 5: Trial(experiment_name='drug_surfactant', index=5, status=TrialStatus.RUNNING, arm=Arm(name='5_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 18, 'surf_2_conc': 76, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'})),
 6: Trial(experiment_name='drug_surfactant', index=6, status=TrialStatus.RUNNING, arm=Arm(name='6_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 59, 'surf_2_conc': 3, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'})),
 7: Trial(experiment_name='drug_surfactant', index=7, status=TrialStatus.RUNNING, arm=Arm(name='7_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 2, 'surf_2_conc': 66, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's6'})),
 8: Trial(experiment_name='drug_surfactant', index=8, status=TrialStatus.RUNNING, arm=Arm(name='8_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 48, 'surf_2_conc': 31, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's6'})),
 9: Trial(experiment_name='drug_surfactant', index=9, status=TrialStatus.RUNNING, arm=Arm(name='9_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 12, 'surf_2_conc': 18, 'drug_conc': 25.0, 'surf_1': 's4', 'surf_2': 's8'})),
 10: Trial(experiment_name='drug_surfactant', index=10, status=TrialStatus.RUNNING, arm=Arm(name='10_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 22, 'surf_2_conc': 10, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'})),
 11: Trial(experiment_name='drug_surfactant', index=11, status=TrialStatus.RUNNING, arm=Arm(name='11_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 55, 'surf_2_conc': 24, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's4'})),
 12: Trial(experiment_name='drug_surfactant', index=12, status=TrialStatus.RUNNING, arm=Arm(name='12_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 12, 'surf_2_conc': 61, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's8'})),
 13: Trial(experiment_name='drug_surfactant', index=13, status=TrialStatus.RUNNING, arm=Arm(name='13_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 38, 'surf_2_conc': 48, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's1'})),
 14: Trial(experiment_name='drug_surfactant', index=14, status=TrialStatus.RUNNING, arm=Arm(name='14_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 1, 'surf_2_conc': 75, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'})),
 15: Trial(experiment_name='drug_surfactant', index=15, status=TrialStatus.RUNNING, arm=Arm(name='15_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 57, 'surf_2_conc': 12, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's3'})),
 16: Trial(experiment_name='drug_surfactant', index=16, status=TrialStatus.RUNNING, arm=Arm(name='16_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 49, 'surf_2_conc': 35, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's5'})),
 17: Trial(experiment_name='drug_surfactant', index=17, status=TrialStatus.RUNNING, arm=Arm(name='17_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 15, 'surf_2_conc': 22, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's5'})),
 18: Trial(experiment_name='drug_surfactant', index=18, status=TrialStatus.RUNNING, arm=Arm(name='18_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 24, 'surf_2_conc': 5, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's2'})),
 19: Trial(experiment_name='drug_surfactant', index=19, status=TrialStatus.RUNNING, arm=Arm(name='19_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 10, 'surf_2_conc': 54, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's7'})),
 20: Trial(experiment_name='drug_surfactant', index=20, status=TrialStatus.RUNNING, arm=Arm(name='20_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 54, 'surf_2_conc': 17, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'})),
 21: Trial(experiment_name='drug_surfactant', index=21, status=TrialStatus.RUNNING, arm=Arm(name='21_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 40, 'surf_2_conc': 43, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's4'})),
 22: Trial(experiment_name='drug_surfactant', index=22, status=TrialStatus.RUNNING, arm=Arm(name='22_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 30, 'surf_2_conc': 2, 'drug_conc': 25.0, 'surf_1': 's3', 'surf_2': 's8'})),
 23: Trial(experiment_name='drug_surfactant', index=23, status=TrialStatus.RUNNING, arm=Arm(name='23_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 63, 'surf_2_conc': 25, 'drug_conc': 25.0, 'surf_1': 's1', 'surf_2': 's5'})),
 24: Trial(experiment_name='drug_surfactant', index=24, status=TrialStatus.RUNNING, arm=Arm(name='24_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 9, 'surf_2_conc': 40, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's4'})),
 25: Trial(experiment_name='drug_surfactant', index=25, status=TrialStatus.RUNNING, arm=Arm(name='25_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 41, 'surf_2_conc': 50, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'})),
 26: Trial(experiment_name='drug_surfactant', index=26, status=TrialStatus.RUNNING, arm=Arm(name='26_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 5, 'surf_2_conc': 32, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's3'})),
 27: Trial(experiment_name='drug_surfactant', index=27, status=TrialStatus.RUNNING, arm=Arm(name='27_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 89, 'surf_2_conc': 8, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's1'})),
 28: Trial(experiment_name='drug_surfactant', index=28, status=TrialStatus.RUNNING, arm=Arm(name='28_0', parameters={'Drug_MW': 0.2063, 'Drug_LogP': 0.3073, 'Drug_TPSA': 0.0373, 'surf_1_conc': 34, 'surf_2_conc': 20, 'drug_conc': 25.0, 'surf_1': 's2', 'surf_2': 's7'})),
 29: Trial(experiment_name='drug_surfactant', index=29, status=TrialStatus.RUNNING, arm=Arm(name='29_0', parameters={'Drug_MW': 0.4045, 'Drug_LogP': 0.4196, 'Drug_TPSA': 0.0728, 'surf_1_conc': 16, 'surf_2_conc': 83, 'drug_conc': 25.0, 'surf_1': 's7', 'surf_2': 's2'})),
 30: Trial(experiment_name='drug_surfactant', index=30, status=TrialStatus.RUNNING, arm=Arm(name='30_0', parameters={'Drug_MW': 0.2962, 'Drug_LogP': 0.4364, 'Drug_TPSA': 0.0493, 'surf_1_conc': 72, 'surf_2_conc': 15, 'drug_conc': 25.0, 'surf_1': 's8', 'surf_2': 's2'})),
 31: Trial(experiment_name='drug_surfactant', index=31, status=TrialStatus.RUNNING, arm=Arm(name='31_0', parameters={'Drug_MW': 0.3528, 'Drug_LogP': 0.281, 'Drug_TPSA': 0.0711, 'surf_1_conc': 14, 'surf_2_conc': 53, 'drug_conc': 25.0, 'surf_1': 's6', 'surf_2': 's1'}))}

In [ ]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,0,IBP,0.2063,0.3073,0.0373,29,6,25.0,s7,s6,35,NaN
1,1,LOV,0.4045,0.4196,0.0728,6,44,25.0,s4,s4,50,NaN
2,2,DCF,0.2962,0.4364,0.0493,4,27,25.0,s2,s6,31,NaN
3,3,GLV,0.3528,0.2810,0.0711,91,1,25.0,s1,s2,92,NaN
4,4,IBP,0.2063,0.3073,0.0373,32,14,25.0,s3,s4,46,NaN
5,5,LOV,0.4045,0.4196,0.0728,18,76,25.0,s8,s1,94,NaN
6,6,DCF,0.2962,0.4364,0.0493,59,3,25.0,s8,s2,62,NaN
7,7,GLV,0.3528,0.2810,0.0711,2,66,25.0,s3,s6,68,NaN
8,8,IBP,0.2063,0.3073,0.0373,48,31,25.0,s4,s6,79,NaN
9,9,LOV,0.4045,0.4196,0.0728,12,18,25.0,s4,s8,30,NaN
10,10,DCF,0.2962,0.4364,0.0493,22,10,25.0,s6,s1,32,NaN
11,11,GLV,0.3528,0.2810,0.0711,55,24,25.0,s2,s4,79,NaN
12,12,IBP,0.2063,0.3073,0.0373,12,61,25.0,s1,s8,73,NaN
13,13,LOV,0.4045,0.4196,0.0728,38,48,25.0,s1,s1,86,NaN
14,14,DCF,0.2962,0.4364,0.0493,1,75,25.0,s2,s7,76,NaN
15,15,GLV,0.3528,0.2810,0.0711,57,12,25.0,s1,s3,69,NaN
16,16,IBP,0.2063,0.3073,0.0373,49,35,25.0,s8,s5,84,NaN
17,17,LOV,0.4045,0.4196,0.0728,15,22,25.0,s2,s5,37,NaN
18,18,DCF,0.2962,0.4364,0.0493,24,5,25.0,s2,s2,29,NaN
19,19,GLV,0.3528,0.2810,0.0711,10,54,25.0,s3,s7,64,NaN
20,20,IBP,0.2063,0.3073,0.0373,54,17,25.0,s1,s5,71,NaN
21,21,LOV,0.4045,0.4196,0.0728,40,43,25.0,s6,s4,83,NaN
22,22,DCF,0.2962,0.4364,0.0493,30,2,25.0,s3,s8,32,NaN
23,23,GLV,0.3528,0.2810,0.0711,63,25,25.0,s1,s5,88,NaN
24,24,IBP,0.2063,0.3073,0.0373,9,40,25.0,s7,s4,49,NaN
25,25,LOV,0.4045,0.4196,0.0728,41,50,25.0,s6,s3,91,NaN
26,26,DCF,0.2962,0.4364,0.0493,5,32,25.0,s6,s3,37,NaN
27,27,GLV,0.3528,0.2810,0.0711,89,8,25.0,s8,s1,97,NaN
28,28,IBP,0.2063,0.3073,0.0373,34,20,25.0,s2,s7,54,NaN
29,29,LOV,0.4045,0.4196,0.0728,16,83,25.0,s7,s2,99,NaN
30,30,DCF,0.2962,0.4364,0.0493,72,15,25.0,s8,s2,87,NaN
31,31,GLV,0.3528,0.2810,0.0711,14,53,25.0,s6,s1,67,NaN

In [ ]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP,LOV,DCF,GLV
0,0,IBP,180.0,0.0,0.0,0.0,0.0,0.0,72.0,348.0,0.0,0.0,780.0,180.0,0.0,0.0,0.0
1,1,LOV,180.0,0.0,0.0,0.0,600.0,0.0,0.0,0.0,0.0,0.0,600.0,0.0,180.0,0.0,0.0
2,2,DCF,180.0,0.0,48.0,0.0,0.0,0.0,324.0,0.0,0.0,0.0,828.0,0.0,0.0,180.0,0.0
3,3,GLV,180.0,1092.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0,0.0,0.0,0.0,180.0
4,4,IBP,180.0,0.0,0.0,384.0,168.0,0.0,0.0,0.0,0.0,0.0,648.0,180.0,0.0,0.0,0.0
5,5,LOV,180.0,912.0,0.0,0.0,0.0,0.0,0.0,0.0,216.0,0.0,72.0,0.0,180.0,0.0,0.0
6,6,DCF,180.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,708.0,0.0,456.0,0.0,0.0,180.0,0.0
7,7,GLV,180.0,0.0,0.0,24.0,0.0,0.0,792.0,0.0,0.0,0.0,384.0,0.0,0.0,0.0,180.0
8,8,IBP,180.0,0.0,0.0,0.0,576.0,0.0,372.0,0.0,0.0,0.0,252.0,180.0,0.0,0.0,0.0
9,9,LOV,180.0,0.0,0.0,0.0,144.0,0.0,0.0,0.0,216.0,0.0,840.0,0.0,180.0,0.0,0.0
10,10,DCF,180.0,120.0,0.0,0.0,0.0,0.0,264.0,0.0,0.0,0.0,816.0,0.0,0.0,180.0,0.0
11,11,GLV,180.0,0.0,660.0,0.0,288.0,0.0,0.0,0.0,0.0,0.0,252.0,0.0,0.0,0.0,180.0
12,12,IBP,180.0,144.0,0.0,0.0,0.0,0.0,0.0,0.0,732.0,0.0,324.0,180.0,0.0,0.0,0.0
13,13,LOV,180.0,1032.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,168.0,0.0,180.0,0.0,0.0
14,14,DCF,180.0,0.0,12.0,0.0,0.0,0.0,0.0,900.0,0.0,0.0,288.0,0.0,0.0,180.0,0.0
15,15,GLV,180.0,684.0,0.0,144.0,0.0,0.0,0.0,0.0,0.0,0.0,372.0,0.0,0.0,0.0,180.0
16,16,IBP,180.0,0.0,0.0,0.0,0.0,420.0,0.0,0.0,588.0,0.0,192.0,180.0,0.0,0.0,0.0
17,17,LOV,180.0,0.0,180.0,0.0,0.0,264.0,0.0,0.0,0.0,0.0,756.0,0.0,180.0,0.0,0.0
18,18,DCF,180.0,0.0,348.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,852.0,0.0,0.0,180.0,0.0
19,19,GLV,180.0,0.0,0.0,120.0,0.0,0.0,0.0,648.0,0.0,0.0,432.0,0.0,0.0,0.0,180.0
20,20,IBP,180.0,648.0,0.0,0.0,0.0,204.0,0.0,0.0,0.0,0.0,348.0,180.0,0.0,0.0,0.0
21,21,LOV,180.0,0.0,0.0,0.0,516.0,0.0,480.0,0.0,0.0,0.0,204.0,0.0,180.0,0.0,0.0
22,22,DCF,180.0,0.0,0.0,360.0,0.0,0.0,0.0,0.0,24.0,0.0,816.0,0.0,0.0,180.0,0.0
23,23,GLV,180.0,756.0,0.0,0.0,0.0,300.0,0.0,0.0,0.0,0.0,144.0,0.0,0.0,0.0,180.0
24,24,IBP,180.0,0.0,0.0,0.0,480.0,0.0,0.0,108.0,0.0,0.0,612.0,180.0,0.0,0.0,0.0
25,25,LOV,180.0,0.0,0.0,600.0,0.0,0.0,492.0,0.0,0.0,0.0,108.0,0.0,180.0,0.0,0.0
26,26,DCF,180.0,0.0,0.0,384.0,0.0,0.0,60.0,0.0,0.0,0.0,756.0,0.0,0.0,180.0,0.0
27,27,GLV,180.0,96.0,0.0,0.0,0.0,0.0,0.0,0.0,1068.0,0.0,36.0,0.0,0.0,0.0,180.0
28,28,IBP,180.0,0.0,408.0,0.0,0.0,0.0,0.0,240.0,0.0,0.0,552.0,180.0,0.0,0.0,0.0
29,29,LOV,180.0,0.0,996.0,0.0,0.0,0.0,0.0,192.0,0.0,0.0,12.0,0.0,180.0,0.0,0.0
30,30,DCF,180.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,864.0,0.0,156.0,0.0,0.0,180.0,0.0
31,31,GLV,180.0,636.0,0.0,0.0,0.0,0.0,168.0,0.0,0.0,0.0,396.0,0.0,0.0,0.0,180.0

In [ ]:
df_vol.sum()

trial_index                                                  496
drug_name      IBPLOVDCFGLVIBPLOVDCFGLVIBPLOVDCFGLVIBPLOVDCFG...
drug                                                      5760.0
s1                                                        6120.0
s2                                                        2880.0
s3                                                        2016.0
s4                                                        2772.0
s5                                                        1188.0
s6                                                        3024.0
s7                                                        2436.0
s8                                                        4416.0
dmso                                                         0.0
water                                                    13548.0
IBP                                                       1440.0
LOV                                                       1440.0
DCF                                                       1440.0
GLV                                                       1440.0
dtype: object

In [ ]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")



print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)



print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: A1
Deep plate will start at: A1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [ ]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_0.py

In [ ]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

    trial_index  success
0             0        1
1             1        1
2             2        0
3             3        1
4             4        1
5             5        1
6             6        1
7             7        0
8             8        1
9             9        1
10           10        0
11           11        0
12           12        1
13           13        0
14           14        0
15           15        0
16           16        1
17           17        0
18           18        0
19           19        0
20           20        0
21           21        0
22           22        0
23           23        0
24           24        1
25           25        0
26           26        0
27           27        1
28           28        1
29           29        0
30           30        1
31           31        1

In [ ]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,0,IBP,0.2063,0.3073,0.0373,29,6,25.0,s7,s6,35,35,1
1,1,LOV,0.4045,0.4196,0.0728,6,44,25.0,s4,s4,50,50,1
2,2,DCF,0.2962,0.4364,0.0493,4,27,25.0,s2,s6,31,100,0
3,3,GLV,0.3528,0.2810,0.0711,91,1,25.0,s1,s2,92,92,1
4,4,IBP,0.2063,0.3073,0.0373,32,14,25.0,s3,s4,46,46,1
5,5,LOV,0.4045,0.4196,0.0728,18,76,25.0,s8,s1,94,94,1
6,6,DCF,0.2962,0.4364,0.0493,59,3,25.0,s8,s2,62,62,1
7,7,GLV,0.3528,0.2810,0.0711,2,66,25.0,s3,s6,68,100,0
8,8,IBP,0.2063,0.3073,0.0373,48,31,25.0,s4,s6,79,79,1
9,9,LOV,0.4045,0.4196,0.0728,12,18,25.0,s4,s8,30,30,1
10,10,DCF,0.2962,0.4364,0.0493,22,10,25.0,s6,s1,32,100,0
11,11,GLV,0.3528,0.2810,0.0711,55,24,25.0,s2,s4,79,100,0
12,12,IBP,0.2063,0.3073,0.0373,12,61,25.0,s1,s8,73,73,1
13,13,LOV,0.4045,0.4196,0.0728,38,48,25.0,s1,s1,86,100,0
14,14,DCF,0.2962,0.4364,0.0493,1,75,25.0,s2,s7,76,100,0
15,15,GLV,0.3528,0.2810,0.0711,57,12,25.0,s1,s3,69,100,0
16,16,IBP,0.2063,0.3073,0.0373,49,35,25.0,s8,s5,84,84,1
17,17,LOV,0.4045,0.4196,0.0728,15,22,25.0,s2,s5,37,100,0
18,18,DCF,0.2962,0.4364,0.0493,24,5,25.0,s2,s2,29,100,0
19,19,GLV,0.3528,0.2810,0.0711,10,54,25.0,s3,s7,64,100,0
20,20,IBP,0.2063,0.3073,0.0373,54,17,25.0,s1,s5,71,100,0
21,21,LOV,0.4045,0.4196,0.0728,40,43,25.0,s6,s4,83,100,0
22,22,DCF,0.2962,0.4364,0.0493,30,2,25.0,s3,s8,32,100,0
23,23,GLV,0.3528,0.2810,0.0711,63,25,25.0,s1,s5,88,100,0
24,24,IBP,0.2063,0.3073,0.0373,9,40,25.0,s7,s4,49,49,1
25,25,LOV,0.4045,0.4196,0.0728,41,50,25.0,s6,s3,91,100,0
26,26,DCF,0.2962,0.4364,0.0493,5,32,25.0,s6,s3,37,100,0
27,27,GLV,0.3528,0.2810,0.0711,89,8,25.0,s8,s1,97,97,1
28,28,IBP,0.2063,0.3073,0.0373,34,20,25.0,s2,s7,54,54,1
29,29,LOV,0.4045,0.4196,0.0728,16,83,25.0,s7,s2,99,100,0
30,30,DCF,0.2962,0.4364,0.0493,72,15,25.0,s8,s2,87,87,1
31,31,GLV,0.3528,0.2810,0.0711,14,53,25.0,s6,s1,67,67,1

# load the results to the optimizer

In [ ]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 0 with data: {'obj_surf_conc': (35.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 1 with data: {'obj_surf_conc': (50.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 2 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 3 with data: {'obj_surf_conc': (92.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 4 with data: {'obj_surf_conc': (46.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 5 with data: {'obj_surf_conc': (94.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 6 with data: {'obj_surf_conc': (62.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 7 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 8 with data: {'obj_surf_conc': (79.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 9 with data: {'obj_surf_conc': (30.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 10 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 11 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 12 with data: {'obj_surf_conc': (73.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 13 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 14 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 15 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 16 with data: {'obj_surf_conc': (84.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 17 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 18 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 19 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 20 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 21 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 22 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 23 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 24 with data: {'obj_surf_conc': (49.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 25 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 26 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 27 with data: {'obj_surf_conc': (97.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 28 with data: {'obj_surf_conc': (54.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 29 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 30 with data: {'obj_surf_conc': (87.0, None)}.
[INFO 07-29 09:22:58] ax.service.ax_client: Completed trial 31 with data: {'obj_surf_conc': (67.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))