# import libraries

In [1]:
import pandas as pd
from ax.service.ax_client import AxClient, ObjectiveProperties
import matplotlib.pyplot as plt
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy   
import time


import sys
sys.path.append('../')
import helper_functions as hf
import math

C:\Users\yunhe\AppData\Local\Temp\ipykernel_11960\2847955232.py:5: DeprecationWarning: Please import from 'ax.generation_strategy.generation_strategy' instead of 'ax.modelbridge.generation_strategy'. The latter is deprecated and will be removed in a future release.
  from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

# generate recommendations

In [2]:
n = hf.get_iteration_number()

for i in range(3):
    print("Very Important: Please Confirm the Iteration Number is Iteration " + str(n))

print()

list_of_drugs = (['IBP'])*4#  + ['LOV']  + ['DCF']  + ['GLV']) * 2

for i in range(3):
    print("Very Important: Please Confirm the Drugs are: ", list_of_drugs)

Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2
Very Important: Please Confirm the Iteration Number is Iteration 2

Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP']
Very Important: Please Confirm the Drugs are:  ['IBP', 'IBP', 'IBP', 'IBP']

In [3]:
time_start = time.time()


df_design= hf.run_optimizer(current_iteration=n, drug_list= list_of_drugs,  bopt = 1)

time_end = time.time()
time_duration = round((time_end - time_start)/60,2)

print("Time taken for optimization: " + str(time_duration) + " mins")
print("Time taken for optimization: " + str(time_duration * 60) + " seconds")

******************************************************************************** 1/4 ********************************************************************************

Update constraints (drug=IBP)：surf_1_conc+surf_2_conc <= 1，>=1

c:\Users\yunhe\anaconda3\envs\drug_surfactant\Lib\site-packages\botorch\optim\optimize_mixed.py:703: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: No feasible point found. Constraint polytope appears empty. Check your constraints.
  best_X, best_acq_val = generate_starting_points(

InfeasibilityError: No feasible point found. Constraint polytope appears empty. Check your constraints.

# process results

In [ ]:
ax_client = hf.load_design_optimizer(n)
ax_client.get_trials_data_frame()

/opt/anaconda3/envs/drug_surfactant/lib/python3.11/site-packages/ax/core/data.py:293: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

,trial_index,arm_name,trial_status,generation_node,obj_surf_conc,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2
0,0,0_0,COMPLETED,GenerationStep_0,35.0,0.2063,0.3073,0.0373,29,6,25.0,s7,s6
1,1,1_0,COMPLETED,GenerationStep_0,50.0,0.2063,0.3073,0.0373,6,44,25.0,s4,s4
2,2,2_0,COMPLETED,GenerationStep_0,31.0,0.2063,0.3073,0.0373,4,27,25.0,s2,s6
3,3,3_0,COMPLETED,GenerationStep_0,92.0,0.2063,0.3073,0.0373,91,1,25.0,s1,s2
4,4,4_0,COMPLETED,GenerationStep_0,46.0,0.2063,0.3073,0.0373,32,14,25.0,s3,s4
5,5,5_0,COMPLETED,GenerationStep_0,94.0,0.2063,0.3073,0.0373,18,76,25.0,s8,s1
6,6,6_0,COMPLETED,GenerationStep_0,62.0,0.2063,0.3073,0.0373,59,3,25.0,s8,s2
7,7,7_0,COMPLETED,GenerationStep_0,68.0,0.2063,0.3073,0.0373,2,66,25.0,s3,s6
8,8,8_0,COMPLETED,GenerationStep_1,21.0,0.2063,0.3073,0.0373,7,14,25.0,s2,s6
9,9,9_0,COMPLETED,GenerationStep_1,23.0,0.2063,0.3073,0.0373,8,15,25.0,s2,s6
10,10,10_0,COMPLETED,GenerationStep_1,22.0,0.2063,0.3073,0.0373,6,16,25.0,s2,s6
11,11,11_0,COMPLETED,GenerationStep_1,23.0,0.2063,0.3073,0.0373,9,14,25.0,s2,s6
12,12,12_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,1,25.0,s2,s6
13,13,12_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,1,25.0,s2,s6
14,14,14_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,1,0,25.0,s2,s6
15,15,12_0,RUNNING,GenerationStep_1,NaN,0.2063,0.3073,0.0373,0,1,25.0,s2,s6

In [ ]:
df_design, df_vol = hf.design_to_vol (n)
df_design

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc
0,12,IBP,0.2063,0.3073,0.0373,0,1,25.0,s2,s6,1,NaN
1,13,IBP,0.2063,0.3073,0.0373,0,1,25.0,s2,s6,1,NaN
2,14,IBP,0.2063,0.3073,0.0373,1,0,25.0,s2,s6,1,NaN
3,15,IBP,0.2063,0.3073,0.0373,0,1,25.0,s2,s6,1,NaN

In [ ]:
df_vol

,trial_index,drug_name,drug,s1,s2,s3,s4,s5,s6,s7,s8,dmso,water,IBP
0,12,IBP,180.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,1188.0,180.0
1,13,IBP,180.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,1188.0,180.0
2,14,IBP,180.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1188.0,180.0
3,15,IBP,180.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,1188.0,180.0

In [ ]:
df_vol[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']].sum()

s1     0.0
s2    12.0
s3     0.0
s4     0.0
s5     0.0
s6    36.0
s7     0.0
s8     0.0
dtype: float64

In [ ]:
plate_well = input("Enter the plate well starting well (e.g., F1): ")
deepplate_well = input("Enter the deep plate well starting well (e.g., F1): ")


print("Please confirm the following information:")
print("Wellplate will start at: " + plate_well)
print("Deep plate will start at: " + deepplate_well)

print()
print("*******************************************************")
print("Continue if correct, or rerun this cell if incorrect.")
print("*******************************************************")

Please confirm the following information:
Wellplate will start at: D1
Deep plate will start at: D1

*******************************************************
Continue if correct, or rerun this cell if incorrect.
*******************************************************

In [ ]:
hf.generate_protocol(df_vol=df_vol, iteration=n, plate_well=plate_well, deepplate_well=deepplate_well)

✅ Successfully wrote to: protocol/otflex_2.py

In [ ]:
df_absorbance = hf.process_absorbance(iteration=n, threshold=0.06)
df_absorbance

   trial_index  success
0            0        0
1            1        0
2            2        0
3            3        0

In [ ]:
results = hf.build_results(n, df_absorbance)
results

,trial_index,drug_name,Drug_MW,Drug_LogP,Drug_TPSA,surf_1_conc,surf_2_conc,drug_conc,surf_1,surf_2,surf_conc,obj_surf_conc,success
0,12,IBP,0.2063,0.3073,0.0373,0,1,25.0,s2,s6,1,100,0
1,13,IBP,0.2063,0.3073,0.0373,0,1,25.0,s2,s6,1,100,0
2,14,IBP,0.2063,0.3073,0.0373,1,0,25.0,s2,s6,1,100,0
3,15,IBP,0.2063,0.3073,0.0373,0,1,25.0,s2,s6,1,100,0

# load the results to the optimizer

In [ ]:
ax_client = hf.load_data_to_optimizer(iteration = n, results = results)
ax_client

[INFO 11-25 15:13:09] ax.service.ax_client: Completed trial 12 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-25 15:13:09] ax.service.ax_client: Completed trial 13 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-25 15:13:09] ax.service.ax_client: Completed trial 14 with data: {'obj_surf_conc': (100.0, None)}.
[INFO 11-25 15:13:09] ax.service.ax_client: Completed trial 15 with data: {'obj_surf_conc': (100.0, None)}.

AxClient(experiment=Experiment(drug_surfactant))